services:
  - type: web
    name: leadiq-ai-backend
    env: python
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: leadiq-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://lohitha-dharma-lead.vercel.app,https://frontend-six-azure-74.vercel.app

databases:
  - name: leadiq-db
    region: singapore
    plan: free
